name: skripsi_kos_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  crypto: ^3.0.3
  equatable: ^2.0.5
  ficonsax: ^0.0.3
  file_picker: ^5.3.3
  flutter:
    sdk: flutter
  flutter_config: ^2.0.2
  flutter_native_splash: ^2.3.1
  flutter_screenutil: ^5.8.4
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.7
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  google_mlkit_text_recognition: ^0.8.1
  http: ^1.1.0
  image_picker: ^1.0.1
  intl: ^0.18.1
  permission_handler: ^10.4.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/animations/
    - .env
